name: 'Get organization repos dependency delta details'
description: 'Get organization repos dependency delta details'
inputs:
  gthub-org-name:
    description: 'Github orhanization name'
    required: true
    default: ''
  gthub-username:
    description: 'Github service account username'
    required: true
    default: ''
  gthub-user:
    description: 'Github service account user'
    required: true
    default: ''
  gthub-user-email:
    description: 'Github service account user email'
    required: true
    default: ''
  gthub-token:
    description: 'Github service account token'
    required: true
    default: ''
  dependency-repo-name:
    description: 'Github repo name for updating the dependency details'
    required: false
    default: ''
  child-pipeline-repo-name:
    description: 'Github repo name for child pipeline'
    required: false
    default: ''

runs:
  using: 'node12'
  main: 'index.js'
